name: 🐛Bug Report
description: Thank you for reporting a bug!
title: "[Bug Report]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    id: new-bug
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Description of the bug
      description: Please describe the issue you experienced in the greatest level of detail possible.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Please list the steps you took before encountering this error.
    validations:
      required: true
  - type: dropdown
    id: device
    attributes:
      label: Device
      description: On what types of devices have you noticed this bug?
      multiple: true
      options:
       - Desktop
       - Mobile
       - Tablet
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: In what browsers have you noticed this bug?
      multiple: true
      options:
       - Chrome
       - Safari
       - Firefox
       - Microsoft Edge
       - Internet Explorer
       - Other
    validations:
      required: true    
  - type: dropdown
    id: severity
    attributes:
      label: How severe would you consider this bug?
      description: Minor means the tool is still useable, while major means the bug renders it unusable.
      multiple: false
      options:
       - Minor
       - Moderate
       - Major
    validations:
      required: true  
  - type: textarea
    id: additional-feedback
    attributes:
      label: Additional feedback (optional)
      description: Please share any additional feedback you have for improving this tool
    validations:
      required: false
  - type: input
    id: contact
    attributes:
      label: Contact details (optional)
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
