name: Bug Report 🐛
description: Report a bug!
title: "[Bug Report]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: checkboxes
    id: new-bug
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Please describe the issue you experienced in the greatest level of detail possible.
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: How severe would you rate this bug?
      description: Minor bugs have little impact on usability while severe bugs render the tool unusable.
      multiple: true
      options:
        - Minor
        - Moderate
        - Severe
     validations:
       required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Internet Explorer
        - Other
     validations:
       required: true
  - type: dropdown
    id: devices
    attributes:
      label: What devices are you seeing the problem on?
      multiple: true
      options:
        - Desktop
        - Mobile
        - Tablet
     validations:
       required: true
